# Generated by Django 4.2.8 on 2024-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamestoreapp', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
                ('cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
